CREATE TABLE admin (
  id INTEGER PRIMARY KEY,
  email TEXT,
  password TEXT,
  token TEXT,
  timestamp INTEGER, -- rename to tokentime, or expiry?
  persistent bool
);
CREATE TABLE episodes (
  id INTEGER PRIMARY KEY AUTOINCREMENT, -- autoincrement not required -- is this forward-facing?
  season INTEGER,
  number INTEGER, -- stop using as an id
  title TEXT,
  artist TEXT, -- default to same as seriesinfo
  shortdesc TEXT,
  longdesc TEXT,
  episodetype TEXT,
  imagefile TEXT, -- if null, use seriesinfo
  mediafile TEXT,
  mediasize INTEGER, -- calculate on upload
  mediatype TEXT, -- this is hardcoded to mp3 for now
  timestamp INTEGER, -- defaults to now, rounds to midnight for now
  duration INTEGER, -- set in browser before upload
  permalink TEXT UNIQUE, -- used for single episode requests, must be unique
  guid TEXT UNIQUE -- generated by the server
);
CREATE TABLE seriesinfo (
  title TEXT,
  artist TEXT,
  copyright TEXT,
  url TEXT,
  owner TEXT,
  email TEXT,
  shortdesc TEXT,
  longdesc TEXT,
  imagefile TEXT,
  mediafolder TEXT,
  category TEXT,
  subcategory TEXT,
  explicit NUMERIC,
  language TEXT,
  seriestype TEXT
);
